name: Compose UI Tests

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ "master" ]

jobs:
  compose-tests:
    if: >
#      github.event.workflow_run.conclusion == 'success' &&
#      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.pull_requests[0].draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Decode google-services.json
        run: echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -d > app/google-services.json
        env:
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedDebugAndroidTest

      - name: Run Compose UI tests
        run: ./gradlew connectedDebugAndroidTest

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: compose_test_report
          path: app/build/reports/androidTests/connected/
